# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5945ffae5479ad84be0ac58aa12429a181c62b2a02cd3edc9858ee5cf9ba3f6ee56e03ac2848f44800e4308e780b68676aa6f9e037a9abcdf751263697223524

test:
  secret_key_base: 793997254ee391d0bcf73d9c0c817661fbd859ded6aed0b736a701754c0dc11d1912ff68ba2b1b248153793cd24e62a0e4cb62600b83f6e22271b0dde205e844

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
